# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gridui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets

class Ui_GridDialog(object):
    def setupUi(self, GridDialog):
        GridDialog.setObjectName("GridDialog")
        GridDialog.resize(270, 140)
        GridDialog.setMinimumSize(QtCore.QSize(270, 140))
        GridDialog.setMaximumSize(QtCore.QSize(270, 140))
        self.lineEditXdir = QtWidgets.QLineEdit(GridDialog)
        self.lineEditXdir.setGeometry(QtCore.QRect(60, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditXdir.setFont(font)
        self.lineEditXdir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditXdir.setObjectName("lineEditXdir")
        self.labelXdir = QtWidgets.QLabel(GridDialog)
        self.labelXdir.setGeometry(QtCore.QRect(20, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelXdir.setFont(font)
        self.labelXdir.setObjectName("labelXdir")
        self.labelYdir = QtWidgets.QLabel(GridDialog)
        self.labelYdir.setGeometry(QtCore.QRect(140, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelYdir.setFont(font)
        self.labelYdir.setObjectName("labelYdir")
        self.lineEditYdir = QtWidgets.QLineEdit(GridDialog)
        self.lineEditYdir.setGeometry(QtCore.QRect(180, 30, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditYdir.setFont(font)
        self.lineEditYdir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditYdir.setObjectName("lineEditYdir")
        self.checkBoxSnap = QtWidgets.QCheckBox(GridDialog)
        self.checkBoxSnap.setGeometry(QtCore.QRect(20, 90, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBoxSnap.setFont(font)
        self.checkBoxSnap.setObjectName("checkBoxSnap")
        self.closeButton = QtWidgets.QPushButton(GridDialog)
        self.closeButton.setGeometry(QtCore.QRect(180, 90, 61, 23))
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(GridDialog)
        QtCore.QMetaObject.connectSlotsByName(GridDialog)

    def retranslateUi(self, GridDialog):
        _translate = QtCore.QCoreApplication.translate
        GridDialog.setWindowTitle(_translate("GridDialog", "Grid Definition"))
        self.labelXdir.setText(_translate("GridDialog", "X dir ="))
        self.labelYdir.setText(_translate("GridDialog", "Y dir ="))
        self.checkBoxSnap.setText(_translate("GridDialog", "Snap to grid"))
        self.closeButton.setText(_translate("GridDialog", "Close"))
